2021-12-29 10:42:49.451 [TRACE_ID:550951f4-0b10-40df-a717-e4a801bf8a57] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 10:42:49.635 [TRACE_ID:550951f4-0b10-40df-a717-e4a801bf8a57] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 10:43:49.729 [TRACE_ID:550951f4-0b10-40df-a717-e4a801bf8a57] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 10:43:49.764 [TRACE_ID:550951f4-0b10-40df-a717-e4a801bf8a57] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 10:56:57.761 [TRACE_ID:608af1f1-35d7-4aaa-8906-5e5f88480707] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 10:56:57.926 [TRACE_ID:608af1f1-35d7-4aaa-8906-5e5f88480707] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 10:57:57.975 [TRACE_ID:608af1f1-35d7-4aaa-8906-5e5f88480707] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 10:57:57.992 [TRACE_ID:608af1f1-35d7-4aaa-8906-5e5f88480707] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:00:45.790 [TRACE_ID:fb69ee3e-9c17-40a9-98d1-b014f5310878] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:00:45.897 [TRACE_ID:fb69ee3e-9c17-40a9-98d1-b014f5310878] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:01:45.946 [TRACE_ID:fb69ee3e-9c17-40a9-98d1-b014f5310878] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:01:45.969 [TRACE_ID:fb69ee3e-9c17-40a9-98d1-b014f5310878] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:02:46.617 [TRACE_ID:02b9c52e-61c5-44ae-91b1-f25eec2ec5ba] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:02:46.713 [TRACE_ID:02b9c52e-61c5-44ae-91b1-f25eec2ec5ba] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:03:46.755 [TRACE_ID:02b9c52e-61c5-44ae-91b1-f25eec2ec5ba] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:03:46.777 [TRACE_ID:02b9c52e-61c5-44ae-91b1-f25eec2ec5ba] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:15:31.034 [TRACE_ID:2b7fa10e-4848-4795-b8c5-48795be6580d] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:15:31.143 [TRACE_ID:2b7fa10e-4848-4795-b8c5-48795be6580d] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:16:31.196 [TRACE_ID:2b7fa10e-4848-4795-b8c5-48795be6580d] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:16:31.228 [TRACE_ID:2b7fa10e-4848-4795-b8c5-48795be6580d] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 60000 ms.
2021-12-29 11:19:17.850 [TRACE_ID:3797fb1f-c153-4148-aa7f-93d2b5513e22] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:19:17.952 [TRACE_ID:3797fb1f-c153-4148-aa7f-93d2b5513e22] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:19:19.998 [TRACE_ID:3797fb1f-c153-4148-aa7f-93d2b5513e22] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.
2021-12-29 11:19:20.014 [TRACE_ID:3797fb1f-c153-4148-aa7f-93d2b5513e22] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.
2021-12-29 11:22:34.588 [TRACE_ID:b8ee7c66-ecc7-42f4-a60a-8719e7fc31a1] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:22:34.700 [TRACE_ID:b8ee7c66-ecc7-42f4-a60a-8719e7fc31a1] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:22:36.753 [TRACE_ID:b8ee7c66-ecc7-42f4-a60a-8719e7fc31a1] ERROR [http-nio-8090-exec-2] o.s.k.s.LoggingProducerListener.error(261): Exception thrown when sending a message with key='123' and payload='{"id":123,"username":"Petros","firstName":"amof","lastName":"amolasf","email":"petors.stergioulas94@...' to topic topic-amos-test-topic:
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.
2021-12-29 11:22:36.767 [TRACE_ID:b8ee7c66-ecc7-42f4-a60a-8719e7fc31a1] ERROR [http-nio-8090-exec-2] o.a.c.c.C.[.[.[.[dispatcherServlet].log(175): Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.] with root cause
org.apache.kafka.common.errors.TimeoutException: Topic topic-amos-test-topic not present in metadata after 2000 ms.
2021-12-29 11:24:31.082 [TRACE_ID:e013daa5-4490-42f7-802e-8427a0343695] ERROR [http-nio-8090-exec-4] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:24:31.283 [TRACE_ID:e013daa5-4490-42f7-802e-8427a0343695] ERROR [http-nio-8090-exec-4] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:33:25.374 [TRACE_ID:805b4d4d-8500-47e1-855b-105d68f26ccd] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:33:25.523 [TRACE_ID:805b4d4d-8500-47e1-855b-105d68f26ccd] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 11:33:31.967 [TRACE_ID:e74a00c1-a082-44b1-bd77-c5c51715a975] ERROR [http-nio-8090-exec-3] i.r.s.d.UserApiDelegateImpl.getUserByName(41): we are error 
2021-12-29 11:33:31.970 [TRACE_ID:e74a00c1-a082-44b1-bd77-c5c51715a975] ERROR [http-nio-8090-exec-3] i.r.s.d.UserApiDelegateImpl.getUserByName(43): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 15:40:31.435 [TRACE_ID:abb47776-0fb4-4065-a7ad-b0c4e2ba4ccb] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(45): we are error 
2021-12-29 15:40:31.772 [TRACE_ID:abb47776-0fb4-4065-a7ad-b0c4e2ba4ccb] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(47): {"id":123,"username":"amo","firstName":"amof","lastName":"amolasf"}
2021-12-29 15:40:33.523 [TRACE_ID:abb47776-0fb4-4065-a7ad-b0c4e2ba4ccb] ERROR [http-nio-8090-exec-2] i.r.s.d.UserApiDelegateImpl.getUserByName(55): {"field":"value"}
